### PR TITLE
Remove Spring

### PR DESCRIPTION
**Pull request by kas-catholic**
Spring is a gem that is supposed to speed up application development
with Rails by keeping some things running in the background. In reality,
this isn't needed on small to medium scale projects with relatively
modern computers, and Spring is infamous for making development harder
because of odd behavior (stale caches, etc). Rails recently [removed
Spring from its default
gems](https://github.com/rails/rails/pull/42997), and we should too.

### CODE REVIEW

**Comment by JohnRDOrazio** [comment]
I trust your judgement on these calls, I have no experience with Rails so let's go ahead and merge, this is a learning process for me.

**Comment by JohnRDOrazio** [comment]
Perhaps the gem cache needs to be cleaned? I'm seeing an error in the github actions:

`Error: The process '/opt/hostedtoolcache/Ruby/3.0.1/x64/bin/bundle' failed with exit code 16`

**Comment by JohnRDOrazio** [comment]
Perhaps just need to remove and recreate the `Gemfile.lock` file?

**Comment by kas-catholic** [comment]
Oops, I should have committed `Gemfile.lock`. Not sure how I missed that... Your other PR looks good to fix it.

**Pull request merged**
