### PR TITLE
Touchups registration form

### PR DESCRIPTION
**Pull request by JohnRDOrazio**

### CODE REVIEW

**Comment by JohnRDOrazio** [comment]
I'm still fairly new to the whole Ruby on Rails approach, so I don't really know a whole lot about validations and all. I've tried to add a few validations here to the registration form. Perhaps can be done better, perhaps more validations can be done and more correctly, anyone can contribute to make this better. I'm doing my best with what I'm reading here and there in the docs...

**Comment by JohnRDOrazio** [comment]
among the validations, there is a basic validation for email format, starts addressing issue #97

**Comment by JohnRDOrazio** [comment]
I initially tested adding a password confirmation to the registration form, and I believe it did work at one point, however in my latest tests I was no longer able to complete registration, I was getting an error that "password confirmation field cannot be empty" (and it wasn't empty!). After a bunch of trial and error without success I gave up on the password confirmation field, I'm not sure how important it is anyway. Once we setup email service, a user could reset their password over email if they can't remember their password or if they typed it wrong the first time.

**Review by kas-catholic — APPROVED** [review]
I think you're very close on the password confirmation. Maybe try this? https://stackoverflow.com/questions/12746589/ruby-on-rails-password-confirmation-validation

The `User` model has a `password_confirmation` field on it (provided by [this](https://github.com/opensourcecatholic/marriage-booklet/blob/8136cc5d4f094ffeac66d558c0e72fe8eb01e532/app/models/user.rb#L4) `has_secure_password` call) and will only save the password if `user.password` and `user.password_confirmation` have both been set and are the same. 

So the idea is to send up both `password` and `password_confirmation` as separate form fields and set them both on the user object. Even doing that without thorough validation would probably be fine - I think the `validates_confirmation_of` helper will make it easier to do the validation correctly.

**Comment by JohnRDOrazio** [comment]
Hi @kas-catholic sorry I took a while to get back to this, have been pretty busy lately. To show you the trouble I'm having, I've enabled the password confirmation field again, and have implemented the `validates_confirmation_of` helper for the password field as you suggested. However I'm still getting the same error: 

```
1 error prohibited this user from being saved:
Password confirmation can't be blank
```

You think you could test this PR as is now, and let me know if you run into the same error?

**Comment by JohnRDOrazio** [comment]
I see that if I comment out the `validates :password_confirmation, presence: true, on: :create` line, registration goes smoothly. I'm not quite understanding why this line would create a `Password confirmation can't be blank` error.

Even in the stackoverflow post you linked to there is this note:

```
NOTE: This check is performed only if password_confirmation is not nil, and by default only on save. 
To require confirmation, make sure to add a presence check for the confirmation attribute:
```

Is this not the correct way to validate the presence of the password confirmation?

**Comment by JohnRDOrazio** [comment]
Actually I think I found the problem, I needed to add `password_confirmation` as an allowed attribute in the User controller.

**Pull request merged**
