### PR TITLE
remove spring and update Gemfile.lock

### PR DESCRIPTION
**Pull request by JohnRDOrazio**
updates rails from 6.1.4 to 6.1.5

### CODE REVIEW

**Comment by JohnRDOrazio** [comment]
I'm now seeing this other error:

`bin/rails:2:in 'load': cannot load such file -- /home/runner/work/marriage-booklet/marriage-booklet/bin/spring (LoadError)
	from bin/rails:2:in '<main>'`

**Comment by JohnRDOrazio** [comment]
ok I think I fixed that error by removing `spring.rb` from the `config` directory, and removing the `load spring` command from the rails binstub.

**Review by kas-catholic — APPROVED** [review]

**Comment by kas-catholic** [comment]
#105 was merged into `main`, but this PR was merged into `remove-spring`. I'll get everything into `main` so it's clean & consistent.

**Comment by kas-catholic** [comment]
Done. Pulling the `main` branch should now include all of this.

**Pull request merged**
