### PR TITLE
Webpacker 6 + Webpack 5 + Tailwind JIT + HMR

### LINKED ISSUE #21: hot reloading
During development, enabling hot reloading of assets (CSS, JS) can be convenient. This avoids manually refreshing the browser every time an asset is updated or changed.

However it seems that hot reloading is not yet working as is, in the current state of the `main` branch.

In my understanding, in order to enable hot reloading, you need to run `bin/webpack-dev-server` (see [here](https://github.com/rails/webpacker#development)).

However when trying to run `bin/webpack-dev-server` (after `yarn install` and `yarn upgrade`), I get this message:
```
The command moved into a separate package: @webpack-cli/serve
Would you like to install serve? (That will run yarn add -D @webpack-cli/serve) (yes/NO) : NO
@webpack-cli/serve needs to be installed in order to run the command.
```

I found [this stackoverflow post](https://stackoverflow.com/a/64947711/394921) that mentions as a solution:
> Apparently, this is an issue with `webpack-cli@4.1.0`. I upgraded to `webpack-cli@4.2.0` and now it works.

So I tried editing `package.json` and upping the version for `webpack-cli` from `"webpack-cli": "^3.3.12"` to `"webpack-cli": "^4.2.0"`, and now I don't get any errors when running `bin/webpack-dev-server`.

### LINKED ISSUE #28: check if i18n-js is useful / needed, and if so, whether it is fully implemented
I added the `i18n-js` gem as well as the `i18n-js` yarn package in PR #24 in order to handle translation strings in javascript files.
However this might not be necessary, if we simply template the javascript files as `erb` files, using the backend **I18n API**.

Though the **erb templating** approach could also get messy. It might be easier to read a plain javascript file. So if we plan on moving forward with `i18n-js`, we'll have to make sure it's fully and correctly implemented, seeing it hasn't yet been fully tested.

I finally got the `I18n` object to be available globally in the application javascript.

It wasn't enough to follow the [github repo readme](https://github.com/fnando/i18n-js), which doesn't take into account webpacker apparently.

And it wasn't even enough to follow suggestions [such as this](https://stackoverflow.com/a/64231813/394921) which fixes the webpacker issue, because the `I18n` object still wasn't available to the whole application, but would have been needed to be `require`d or `import`ed in every javascript file that wanted to use it.

In order to solve this, I also had to add `i18n-js` to the webpacker json configuration, under the **ProviderPlugin** section, alongside `jQuery` and `$`. However `I18n` in this case is pointing directly at the `node-modules` instance, and not at the `js.erb` which we created from the above suggestion.

In the meantime, `I18n.translations` is now being defined / imported in the `js.erb` which we created. So is `I18n.translations` actually available?

Also, do we need to configure the generation of `.json` language files from the `.yml` translation files? Or are the translation strings already available through `I18n.translations`?

We will need some trial and error and testing to see if this needs more work in order to function correctly, and we need to decide whether to follow this approach rather than following the **erb templating** approach.

For example, if a new translation key is defined in a javascript file, will the `i18n-tasks` be able to pick it up, if we're not using **erb templating**?

### LINKED ISSUE #39: enable tailwind JIT mode
Tailwind v2.1+ has a new JIT mode which you can make use of, for faster and more efficient compiling, especially when creating custom variants.
See here for information: https://tailwindcss.com/docs/just-in-time-mode

Obviously, as we saw in issue #38 , it is not enough to add `mode: 'jit'` to the tailwind config.

Following the information from the documentation above, we would at least have to add a bit more configuration.

> Since JIT mode generates your CSS on-demand by scanning your template files, it’s crucial that you configure the `purge` option in your `tailwind.config.js` file with all of your template paths, otherwise your CSS will be empty:

```diff
 // tailwind.config.js
  module.exports = {
    mode: 'jit',
+   // These paths are just examples, customize them to match your project structure
+   purge: [
+     './public/**/*.html',
+     './src/**/*.{js,jsx,ts,tsx,vue}',
+   ],
    theme: {
      // ...
    }
    // ...
  }
```

If for any reason it still doesn't work after that, perhaps check out https://dev.to/davidteren/getting-started-with-rails-6-1-tailwindcss-jit-webpacker-postcss-8-25g7

### LINKED ISSUE #57: `assets pipeline` vs `webpack`
Seeing that on the production instance, the scaffold generated stylesheet (in this case, `/app/assets/stylesheets/projects.scss`) which should apply to the generated resource (in this case `projects`), is not actually being applied:

we need to figure out how to handle the **assets pipeline** vs the **webpack** workflow when it comes to stylesheets.

Here is a good blog post about this: https://mariochavez.io/desarrollo/2020/05/19/from-the-asset-pipeline-to-webpack/

Perhaps we should try to do away with the **assets pipeline** altogether, and use only a webpack workflow? If so, how would this work for stylesheets that should apply to a whole resource (such as `projects`), and all views associated with that resource?

### PR DESCRIPTION
**Pull request by JohnRDOrazio**
This is a pretty significant PR.

I've done quite a bit of reading up on different blog posts, stackoverflow posts, and github readme's.

I started putting a bunch of the information together in a [wiki page here](https://github.com/opensourcecatholic/marriage-booklet/wiki/5-Webpack-setup).

In the end, to get everything working fairly nicely, I wound up updating **Webpacker** to the latest version [6.0.0.beta.7](https://github.com/rails/webpacker/tree/v6.0.0.beta.7) from the github repo.

This allows to use **Webpack 5**. So I also updated to the latest webpack v5.

I updated Tailwind to the latest version and enabled JIT mode.

And to get HMR working I got rid of `webpack-dev-server` and I added `webpack-plugin-serve` .

I disabled **sprockets**, and got rid of the **asset pipeline**, so that everything is served by webpack from `app/packs`.

From what I understand so far, **entrypoints** are basically the highest level JS files. So the main entrypoint is the `application.js` which we include in our `layouts/application.html.erb`, and is served to the whole application.

However, since we don't want to include a resource level JS (for example, `projects.js`) for the whole application, and we don't want to include a page level JS (for example, `projectNew.js`) for the whole application, we can treat these as entrypoints. Whereas any JS files that will be included into any of the entrypoint files, we can put into the `app/packs/src` directory (kind of like `node_modules`).

With all this, everything is just about working right. Compiling assets is almost working perfectly.

Still have to iron out a few things:
* when having multiple entrypoints, and not just `application.js`, I think we have to define the output file in a dynamic manner, because I'm seeing this error: `ERROR in Conflict: Multiple assets emit different content to the same filename js/.br`, which some say comes from the fact that you have to use a dynamic output filename rather than a static filename in `webpacker.config.js` (which we don't yet have? we have `webpacker.yml`... Is `webpacker.yml` supposed to take the place of `webpacker.config.js`?)
* how exactly are images supposed to be included, in a rails view? there are helpers such as `image_pack_tag` and even `inline_svg_pack_tag`, however they are not finding the images in `app/packs/images`. Whereas I can import an image in javascript with `import imgPath from '../images/wedding-rings.svg'`, and that works just fine. I read that you should be able to solve this by adding `require.context('../images', true)` in `application.js`, and then all of the images in that folder will be included by webpack and will be accessible underneath the `media/` path, however it doesn't seem to have solved my issue on the home page where I am trying to use `inline_svg_pack_tag("media/images/cover.svg")`

Should fix:
* fixes #57 
* fixes #39 
* fixes #21 
* fixes #28

### CODE REVIEW

**Comment by JohnRDOrazio** [comment]
I also had to regenerate the `tailwind.config.js`, since it was causing an error (something about color flattening).
Probably some settings changed slightly between versions.
After regenerating with `npx tailwindcss init --full` the error went away.
I also regenerated the `postcss.config.js` with `npx tailwindcss init -p`.
Probably could have done them both in one step, but I was reading bits and pieces here and there...

**Comment by JohnRDOrazio** [comment]
well I think I fixed the erb loader, had to use a newer syntax. I was able to use the [README](https://github.com/usabilityhub/rails-erb-loader#usage) as a reference.

**Comment by JohnRDOrazio** [comment]
fixes #57 
fixes #39 
fixes #21 
fixes #28

**Comment by JohnRDOrazio** [comment]
I thought that maybe the fix for the error `ERROR in Conflict: Multiple assets emit different content to the same filename js/.br` was due to a setting for the output filename, as [talked about here](https://stackoverflow.com/questions/42148632/conflict-multiple-assets-emit-to-the-same-filename).

However, upon inspecting the webpacker configuration generated by the `webpacker.yml` (and after merging with custom configurations in `config/webpack/base.js`), I see that the output filename is already being handled dynamically:

```json
{
  "mode": "development",
  "output": {
    "filename": "[name]-[hash].js",
    "chunkFilename": "js/[name]-[contenthash].chunk.js",
    "hotUpdateChunkFilename": "js/[id]-[hash].hot-update.js",
    "assetModuleFilename": "static/[hash][ext][query]",
    "path": "/home/johnrdorazio/development/marriage-booklet/public/packs",
    "publicPath": "/packs/"
  },
  "entry": {
    "application": [
      "/home/johnrdorazio/development/marriage-booklet/app/packs/entrypoints/application.js",
      "/home/johnrdorazio/development/marriage-booklet/app/packs/entrypoints/application.scss"
    ],
    "projectPreview": "/home/johnrdorazio/development/marriage-booklet/app/packs/entrypoints/projectPreview.js",
    "projectsIndex": "/home/johnrdorazio/development/marriage-booklet/app/packs/entrypoints/projectsIndex.js",
    "projectsNew": "/home/johnrdorazio/development/marriage-booklet/app/packs/entrypoints/projectsNew.js"
  },
  "resolve": {
    "extensions": [
      ".js",
      ".mjs",
      ".ts",
      ".js",
      ".js.erb",
      ".css",
      ".scss",
      ".json",
      ".svg",
      ".png",
      ".jpg",
      ".jpeg",
      ".gif"
    ],
    "modules": [
      "/home/johnrdorazio/development/marriage-booklet/app/packs",
      "node_modules"
    ]
  },
  ---
}
```

**Comment by kas-catholic** [comment]
Great job researching all this! A lot changed in Rails 6 and a lot of the Rails 6 webpacker stuff is new to me. Your docs in this PR and the wiki look great. Everything seems to work for me locally except the SVG.

**Pull request merged**
