### PR TITLE
projects scaffolding

### PR DESCRIPTION
**Pull request by JohnRDOrazio**
I started from a clean branch, using the rails scaffolding to setup the **projects** resources.

These are the steps I took to generate this (I found out from trial and error and the messages on the command line that you don't need to explicitly create the `id` field, it will be generated automatically):

```ruby
$ bundle exec rails generate scaffold Project liturgy:integer brideFirstName:string brideLastName:string groomFirstName:string groomLastName:string celebrantNamePrefix:string celebrantFirstName:string celebrantLastName:string church:string city:string weddingdate:datetime
$ bundle exec rails db:migrate RAILS_ENV=development
```

I suppose I can apply some of the tailwind styling to this branch, so we wouldn't even have to merge PR #18 .

### CODE REVIEW

**Comment by JohnRDOrazio** [comment]
This PR is now at the point that it pretty much mirrors the styling of PR #18 , so it can take the place of PR #18.

However I have no notion whatsoever of how the tests should be carried out. Why exactly are they failing? Do we need to update something on the Github side of things? The scaffolding was done using `bundle exec rails generate scaffold`, and since then the tests have been failing on push.

**Comment by JohnRDOrazio** [comment]
well then, exploring the error messages from the functional tests, I found that the `locale` parameter needed to be set for the test environment. And after running a number of tests locally (I figured out how to do that too now, with `bundle exec rails test -b test/controllers/projects_controller_test.rb`) and experimenting with different solutions (for example see [this discussion](https://github.com/rspec/rspec-rails/issues/255)), I found that the simplest fix was to add `routes.default_url_options[:locale]= I18n.default_locale` in the `Rails.application.configure do` section.

With that, tests are now passing.

**Comment by JohnRDOrazio** [comment]
commit 0ed5332ed9642dd26beed07bca1e76e2b43213d4 fixes issue #22

**Comment by JohnRDOrazio** [comment]
commit 2946db3 fixes issue #23

**Review by kas-catholic — APPROVED** [review]

**Comment by kas-catholic** [comment]
Big PR, but it looks good to me. Merging this will give us a foundation to start building on. Is it ready to be merged?

**Pull request merged**
